### ISSUE TITLE
[BUG] Infinite loading Paper Trail

### ISSUE THREAD

**Issue by jonathanafranio** [PenguinOfWar/strapi-plugin-paper-trail#11]
When testing the plugin with a robust base, when entering the registry edit, the Paper Trail plugin box had infinite pre-loading, due to the high number of edits and never finished loading and after a long time it blocked the request.
Is there any parameter that limits the number of records in the history, for example, only pulling the 3 latest updates?
I looked for something like this in the documentation in the readme but I didn't find anything. :(

Strapi version: v4.10.2
Node Version: v18.19

![image2](https://github.com/PenguinOfWar/strapi-plugin-paper-trail/assets/768332/19d953b4-0b43-477d-9623-59cadf15ed01)

**Comment by PenguinOfWar** [comment]
Oof, that is a bad one. How many records is it trying to pull back? I will reproduce and try to fix this.

**Comment by jonathanafranio** [comment]
> Oof, that is a bad one. How many records is it trying to pull back? I will reproduce and try to fix this.

Hey how's it going? So, it's a large database, the record that has the least updates contains 20 record edits.

**Comment by PenguinOfWar** [comment]
@jonathanafranio going good thanks! Please try updating to `v0.4.0`. I've added pagination to the trails list which limits the number of fetched records.

https://www.npmjs.com/package/strapi-plugin-paper-trail
https://github.com/PenguinOfWar/strapi-plugin-paper-trail/releases/tag/v0.4.0

**Comment by PenguinOfWar** [comment]
@jonathanafranio as far as I can tell from my tests and running this on my own production apps, this seems to have solved the problem. I’m going to close this as resolved, but if the issue persists please let me know and I will re-open. Thanks for the bug report!
