### ISSUE TITLE
[FEATURE REQUEST] Capture entire change as raw JSON to display on Trail admin screen

### ISSUE THREAD

**Issue by DarrylWalkerJacobs** [PenguinOfWar/strapi-plugin-paper-trail#13]
Similar to:

![image](https://github.com/PenguinOfWar/strapi-plugin-paper-trail/assets/94604001/6c977efb-6b8a-4780-8c4d-72d0babe2207)

**Comment by PenguinOfWar** [comment]
Thanks, me.
