### ISSUE TITLE
[BUG] Rendered more hooks than during the previous render.

### ISSUE THREAD

**Issue by diego-sbtlab** [PenguinOfWar/strapi-plugin-paper-trail#17]
When I use strapi-plugin-paper-trail plugin and i access any single-type model in the content-manger, I get this follow error:
Minified React error #310 -> Rendered more hooks than during the previous render. This error prevents the page from rendering, leaving it completely blank.

This error only happens with strapi  version > 4.20.0. 
This error doesn't happen with collections, only using single-types.

I'm stuck on version 4.15.5 because of this issue of this plugin.

**Comment by PenguinOfWar** [comment]
Thanks for the bug report. I’ll check this out.

**Comment by PenguinOfWar** [comment]
@diego-sbtlab Unfortunately I can't replicate this on strapi `v4.20.1`, however while checking this out I did notice the support for single types just wasn't working.

I've fixed the single type support in Paper Trail `v0.6.0` that has just gone out now and verified it's working. Can you update to this version and try again on the latest strapi version?

If the error persists on the latest versions of both strapi and Paper Trail, please let me know what other plugins you are using as these may be causing a conflict with Paper Trail. I can then test my local with your plugin setup.

https://github.com/PenguinOfWar/strapi-plugin-paper-trail/releases/tag/v0.6.0
https://www.npmjs.com/package/strapi-plugin-paper-trail/v/0.6.0

**Comment by PenguinOfWar** [comment]
Closing as assuming resolved based on testing. Let me know if you are still struggling and I will reopen!
