### ISSUE TITLE
[BUG] ReferenceError: React is not defined

### ISSUE THREAD

**Issue by diego-sbtlab** [PenguinOfWar/strapi-plugin-paper-trail#21]
### Required System information

- Node.js version:  v18.19.1
- NPM version: 10.2.4
- Strapi version: 4.23.0
- Database: postgres
- Operating system: Linux
- Is your project Javascript or Typescript: Tpescript

### Describe the bug

I'm getting the 'ReferenceError: React is not defined' error due to the absence of the React import in TrailsTablePagination.js.

**Comment by PenguinOfWar** [comment]
Thanks @diego-sbtlab I’ll get a fix out promptly.

**Comment by PenguinOfWar** [comment]
@diego-sbtlab Please try version `6.0.1` just published to npm. Please re-open and @ me if this doesn't solve your issue.

https://github.com/PenguinOfWar/strapi-plugin-paper-trail/releases/tag/v0.6.1
https://www.npmjs.com/package/strapi-plugin-paper-trail/v/0.6.1
